#!/usr/bin/env bash
# gen-verify-gate.sh — generate a sensible-default L0 verify gate for a repo.
# bash 3.2 compatible (macOS default). No mapfile / associative arrays.
#
# The generated .verify.sh chains ONLY checks that already exist in the repo.
# It never invents a test suite. Repos with nothing runnable get an honest
# no-op gate that FAILS loud (exit 1) so it can't be mistaken for a real pass.
#
# For JS repos it also wires an npm "verify" script (via a tiny node one-liner)
# so `npm run verify` works uniformly — unless a "verify" script already exists.
#
# Usage:
#   gen-verify-gate.sh [TARGET_DIR]            # default: current directory
#   gen-verify-gate.sh --dry-run [TARGET_DIR]  # print what WOULD be written
#
# Idempotent: if .verify.sh already exists it is left untouched (reported).
# Exit: 0 ok, 1 target not a directory.

set -uo pipefail

DRY_RUN=0
TARGET="."
while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) grep '^#' "$0" | sed 's/^# \?//'; exit 0 ;;
    *) TARGET="$1"; shift ;;
  esac
done

TARGET="$(cd "$TARGET" 2>/dev/null && pwd -P || true)"
[ -z "$TARGET" ] && { echo "ERROR: target is not a directory"; exit 1; }
[ -d "$TARGET" ] || { echo "ERROR: target is not a directory"; exit 1; }
cd "$TARGET" || exit 1

# ---- helper: does package.json have script <name>? -------------------------
has_npm_script() {  # has_npm_script <name>
  local name="$1"
  [ -f package.json ] || return 1
  # grep the "scripts" block loosely: "name": present as a key
  grep -Eq "\"$name\"[[:space:]]*:" package.json 2>/dev/null
}

# ---- detect stack ----------------------------------------------------------
HAS_PKG=0; [ -f package.json ] && HAS_PKG=1
HAS_PY=0
if [ -f pyproject.toml ] || [ -f requirements.txt ] || [ -f setup.py ] \
   || ls ./*.py >/dev/null 2>&1 || ls scripts/*.py >/dev/null 2>&1; then
  HAS_PY=1
fi
HAS_GO=0; [ -f go.mod ] && HAS_GO=1

# ---- build the ordered check list (only real, present checks) --------------
# Each entry is a shell line the gate will run in order, stop-on-fail.
CHECKS=""        # newline-separated shell commands
CHECK_LABELS=""  # human labels for the report
STACK="none"

add_check() {  # add_check <label> <command>
  CHECK_LABELS="${CHECK_LABELS}${1}\n"
  CHECKS="${CHECKS}run_step \"$1\" $2\n"
}

if [ "$HAS_PKG" -eq 1 ]; then
  STACK="js"
  # npm runner: prefer npm; the generated gate resolves at runtime
  for s in typecheck tsc lint test build; do
    if has_npm_script "$s"; then
      add_check "npm run $s" "npm run $s"
    fi
  done
  # fall back to a common "check" script if nothing above matched
  if [ -z "$CHECKS" ] && has_npm_script check; then
    add_check "npm run check" "npm run check"
  fi
elif [ "$HAS_PY" -eq 1 ]; then
  STACK="py"
  # ruff if configured (pyproject [tool.ruff] or ruff.toml or .ruff.toml)
  if grep -q "tool.ruff" pyproject.toml 2>/dev/null || [ -f ruff.toml ] || [ -f .ruff.toml ]; then
    add_check "ruff check" "run_py_tool ruff check ."
  fi
  # pytest if there are tests
  if [ -d tests ] || ls test_*.py >/dev/null 2>&1 || ls tests/*.py >/dev/null 2>&1 \
     || ls ./*/test_*.py >/dev/null 2>&1; then
    add_check "pytest" "run_py_tool pytest -q"
  fi
elif [ "$HAS_GO" -eq 1 ]; then
  STACK="go"
  add_check "go build ./..." "go build ./..."
  add_check "go vet ./..."   "go vet ./..."
  add_check "go test ./..."  "go test ./..."
fi

# ---- render the gate script -------------------------------------------------
GATE_PATH=".verify.sh"

render_gate() {
  cat <<'GATE_HEADER'
#!/usr/bin/env bash
# .verify.sh — L0 ground-truth gate (auto-generated by gen-verify-gate.sh).
# Runs the repo's real checks in order, stops on first failure, prints the
# actual exit code. Regenerate with:
#   path/to/my-robot/template/gen-verify-gate.sh .
# (or re-run bootstrap after adding tests — existing .verify.sh is left untouched,
#  so remove it first if you want a fresh generated gate)
#
# HONESTY CONTRACT: this gate only runs checks that exist. It does NOT invent
# a test suite. If a repo has no runnable checks it exits 1 on purpose so a
# missing gate can never look like a passing one.
set -uo pipefail
cd "$(dirname "$0")"

FAILED=0
run_step() {  # run_step <label> <cmd...>
  local label="$1"; shift
  echo "── $label ──"
  if "$@"; then
    echo "   ✓ $label"
  else
    rc=$?
    echo "   ✗ $label (exit $rc)"
    FAILED=1
    return $rc
  fi
}

# Python tool runner: prefer the repo's .venv, then .venv-lancedb, then PATH.
# PYTHONPATH/VIRTUAL_ENV are unset so the Hermes runtime's site-packages can't
# shadow the repo venv (this pollution bit the fleet index before).
run_py_tool() {  # run_py_tool <tool> <args...>
  local tool="$1"; shift
  if [ -x ".venv/bin/$tool" ]; then env -u PYTHONPATH -u VIRTUAL_ENV ".venv/bin/$tool" "$@"; return $?; fi
  if [ -x ".venv-lancedb/bin/$tool" ]; then env -u PYTHONPATH -u VIRTUAL_ENV ".venv-lancedb/bin/$tool" "$@"; return $?; fi
  if command -v "$tool" >/dev/null 2>&1; then env -u PYTHONPATH -u VIRTUAL_ENV "$tool" "$@"; return $?; fi
  echo "   (tool '$tool' not found — install it or point .venv at it)"
  return 127
}

GATE_HEADER

  if [ -z "$CHECKS" ]; then
    cat <<GATE_EMPTY
echo "No runnable checks detected in this repo ($STACK)."
echo "Define real checks (tests, lint, typecheck, build) and regenerate:"
echo "  path/to/my-robot/template/gen-verify-gate.sh ."
echo "Exiting 1 — an undefined gate must never report success."
exit 1
GATE_EMPTY
  else
    printf '%b' "$CHECKS"
    cat <<'GATE_FOOTER'

if [ "$FAILED" -eq 0 ]; then
  echo "verify: PASS"
  exit 0
else
  echo "verify: FAIL"
  exit 1
fi
GATE_FOOTER
  fi
}

# ---- write / report ---------------------------------------------------------
echo "== gen-verify-gate =="
echo "target: $TARGET"
echo "stack:  $STACK"
if [ -n "$CHECK_LABELS" ]; then
  echo "checks: $(printf '%b' "$CHECK_LABELS" | grep -v '^$' | paste -sd',' - | sed 's/,/, /g')"
else
  echo "checks: (none detected — honest fail-loud gate)"
fi

if [ -f "$GATE_PATH" ]; then
  echo "result: EXISTED — $GATE_PATH left untouched"
elif [ "$DRY_RUN" -eq 1 ]; then
  echo "result: WOULD WRITE $GATE_PATH"
  echo "-------- preview --------"
  render_gate
  echo "-------- /preview -------"
else
  render_gate > "$GATE_PATH"
  chmod +x "$GATE_PATH"
  echo "result: WROTE $GATE_PATH"
fi

# ---- wire npm "verify" script for JS repos ---------------------------------
if [ "$STACK" = "js" ]; then
  if has_npm_script verify; then
    echo "npm:    verify script already exists — left untouched"
  elif [ "$DRY_RUN" -eq 1 ]; then
    echo "npm:    WOULD add \"verify\": \"bash .verify.sh\" to package.json"
  else
    # Use node to safely edit package.json (preserve formatting best-effort)
    if command -v node >/dev/null 2>&1; then
      node -e '
        const fs=require("fs");
        const p="package.json";
        const j=JSON.parse(fs.readFileSync(p,"utf8"));
        j.scripts=j.scripts||{};
        if(!j.scripts.verify){ j.scripts.verify="bash .verify.sh"; }
        fs.writeFileSync(p, JSON.stringify(j,null,2)+"\n");
      ' && echo "npm:    added \"verify\": \"bash .verify.sh\"" \
        || echo "npm:    FAILED to edit package.json (left untouched)"
    else
      echo "npm:    node not found — skipped wiring verify script"
    fi
  fi
fi

echo "Done."
